cas.server.name=http://localhost:8080
cas.server.prefix=${cas.server.name}/cas

logging.config=file:/etc/cas/config/log4j2.xml

server.port=8080
server.ssl.enabled=false

cas.service-registry.json.location=file:/etc/cas/services

cas.authn.attribute-repository.stub.attributes.name=casuser
cas.authn.attribute-repository.stub.attributes.email=casuser@example.org
cas.authn.attribute-repository.stub.attributes.email_verified=casuser@example.org

cas.authn.oauth.user-profile-view-type=FLAT

# cas.authn.accept.users=

cas.authn.oauth.code.time-to-kill-in-seconds=300
cas.authn.oauth.code.number-of-uses=100